1	git://github.com/jknack/handlebars.java.git
2	#DEP#org.apache.maven.plugin-tools:maven-plugin-annotations
3	#DEP#com.github.jknack:handlebars-humanize
4	#DEP#org.codehaus.plexus:plexus-utils
5	#DEP#org.springframework:spring-test
6	#DEP#com.github.jknack:handlebars-jackson2
7	#DEP#com.google.guava:guava
8	#DEP#com.github.mfornos:humanize-slim
9	#DEP#junit:junit
10	#DEP#org.pegdown:pegdown
11	#DEP#org.yaml:snakeyaml
12	#DEP#org.easymock:easymock
13	#DEP#org.mozilla:rhino
14	#DEP#org.springframework:spring-webmvc
15	#DEP#args4j:args4j
16	#DEP#org.apache.commons:commons-lang3
17	#DEP#ch.qos.logback:logback-classic
18	#DEP#org.apache.maven:maven-project
19	#DEP#org.slf4j:slf4j-api
20	#DEP#org.antlr:antlr4-runtime
21	#DEP#org.codehaus.jackson:jackson-mapper-asl
22	#DEP#org.eclipse.jetty.orbit:javax.servlet
23	#DEP#com.github.jknack:handlebars
24	#DEP#joda-time:joda-time
25	#DEP#com.google.javascript:closure-compiler
26	#DEP#com.github.jknack:handlebars-markdown
27	#DEP#org.powermock:powermock-api-easymock
28	#DEP#org.powermock:powermock-module-junit4
29	#DEP#org.apache.commons:commons-io
30	#DEP#commons-io:commons-io
31	#DEP#org.apache.maven:maven-core
32	#DEP#org.eclipse.jetty:jetty-server
33	#DEP#org.eclipse.jetty:jetty-servlet
34	#DEP#com.fasterxml.jackson.core:jackson-databind
35	#DEP#org.apache.maven:maven-plugin-api
36	#DEP#javax.servlet:servlet-api
37	#DEP#org.eclipse.jetty:jetty-webapp
